blog/urls.py
from django.urls import path
from . import views

from .feeds import LatestPostsFeed

urlpatterns = [
    path("", views.post_list, name="post_list"),
    #path("", views.PostListView.as_view(), name="post_list"),
    path(r'^tag/(?P<tag_slug>[-\w]/$', views.post_list, name='post_list_by_tag'),
    path(r"^(P?<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/"\
         r"(?P<post>[-\w]+)/$",
         views.post_detail,
         name="post_detail"),
    path('feed/', LatestPostsFeed(), name="post_feed"),
    ]

main/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    #("blog.urls" - incuded url-file, "blog" - app_name)
    path("blog/", include(("blog.urls", "blog"), namespace='blog')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
]

blog/models.py
# Create your models here.
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class Post(models.Model):
    def get_absolute_url(self):
        """returns the canonical address of the object"""
        return reverse('blog:post_detail',
                        args=[self.publish.year,
                              self.publish.strftime('%m'),
                              self.publish.strftime('%d'),
                              self.slug])

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    #slug - label, contains only letters, numbers, underscores, or hyphens
    #the unique_for_date parameter allows you to build unique URLs that contain the title of the post and the date it was published
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms

from .models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
# Create your views here.
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
#from django.views.generic import ListView
from taggit.models import Tag
from .models import Post, Comment
from .forms import CommentForm

'''
class PostListView(ListView):
    queryset = Post.objects.filter(status="published")
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'
    '''

def post_list(request, tag_slug=None):
    object_list = Post.objects.filter(status="published")
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page not integer deliver first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(status="published", tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})

blog/templates/blog/base.html
<!DOCTYPE html>
{% load blog_tags %}
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
            <h2>Мой блоґ</h2>
            <p>Гэта мой блоґ. Я напісаў ужо {% total_posts %} пастоў.</p>
            <p><a href="{% url 'blog:post_feed' %}">Падпішыцеся на мой RSS-канал</a></p>

            <h3>Апошнія пасты</h3>
            {% show_latest_posts 3 %}

            <h3>Пасты з найбольшаю колькасцью каментарыяў</h3>
            {% get_most_commented_posts as most_commented_posts %}
            <ul>
                {% for post in most_commented_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="tags">
        Тэґі:
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <p class="date">
        Апублікаванна {{ post.publish|date:"d-m-Y у G:i" }} карыстальнікам {{ post.author }}
        <!--
            d - Day of the month, 2 digits with leading zero (from '01' to '31');
            m - Month, 2-digit with leading zeros (from '01' to '12');
            Y - Year, 4 digits ('1999');
            у - Belarusian Cyrillic letter u;
            H - Hour, 24-hour format (from '0' to '23');
            i - Minutes (from '00' to '59')
            -->
    </p>
    {{ post.body|markdown }}

    <h2>Падобныя пасты</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Падобных пастоў пакуль няма.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} {{ total_comments|by_plural:"каментар, каментары, каментароў" }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Каментар {{ forloop.counter }} ад {{ comment.name }}
                {{ comment.created|date:"d-m-Y у G:i" }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>Каментароў пакуль няма.</p>
    {% endfor %}

    <h2>Дадаць новы каментар</h2>
    <form action="{{ post.get_absolute_url }}" method="post">
        {% csrf_token %}
        <div class="comment-form">
            <p>
                <label for="id_name">Імя:</label>
                <input type="text" name="name" maxlength="80" required="" id="id_name">
            </p>
            <p>
                <label for="id_email">Імэйл:</label>
                <input type="email" name="email" required="" id="id_email">
            </p>
            <p>
                <label for="id_body">Тэкст:</label>
                <textarea name="body" cols="40" rows="10" required="" id="id_body" style="height: 220px; width:842px;"></textarea>
            </p>
        </div>
        <p><input type="submit" value="Дадаць каментар"></p>
    </form>
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Мой Блоґ{% endblock %}
{% block content %}
    <h1>Mой Блоґ</h1>
    {% if tag %}
        <h2>Пасты адзначаныя тэґам "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <div class="post">
            <h2>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h2>
            <p class="tags">
                Тэґі:
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p class="date">
                Апублікаванна {{ post.publish|date:"d-m-Y у G:i" }} карыстальнікам {{ post.author }}
            </p>
            <!--
            d - Day of the month, 2 digits with leading zero (from '01' to '31');
            m - Month, 2-digit with leading zeros (from '01' to '12');
            Y - Year, 4 digits ('1999');
            у - Belarusian Cyrillic letter u;
            H - Hour, 24-hour format (from '0' to '23');
            i - Minutes (from '00' to '59')
            -->
            <!--truncatewords truncates the value to the specified number of words-->
            <!--truncatewords_html truncates a line after a certain number of words, avoiding unclosed HTML tags-->
            {{ post.body|markdown|truncatewords_html:30 }}
        </div>
        <hr>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
    <!--{% include "pagination.html" with page=page_obj %}-->
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Папярэдняя</a>
        {% endif %}
        <span class="current">
            Старонка {{ page.number }} з {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Наступная</a>
        {% endif %}
    </span>
</div>